### ISSUE TITLE
Make it acessible through the command line

### ISSUE THREAD

**Issue by Yuri-M-Dias** [gustavosotnas/quick-deb-builder#17] opened 2017-01-19 10:37 UTC
Albeit it's fine to use it with a nice GUI, it's not good for cases when you don't have an X server running/headless. Also, not very nice to make scripts to it without being capable of doing that.
I don't currently know the code, so I can't know if it'll be an easy change, but I'll try looking into it to make a pull request later.

**Comment by gustavomdsantos** [comment] 2017-01-19 11:10
@Yuri-M-Dias, Quick DEB Builder is already acessible through command line since version [1.2.0](https://github.com/gustavosotnas/quick-deb-builder/releases/tag/v1.2.0). Closing issue because is a duplicate of issue #10.

**Closed as completed by gustavomdsantos** 2017-01-19 11:10 UTC
Labels: duplicate
